# Generated by Django 5.0.8 on 2024-08-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
