# Generated by Django 5.0.8 on 2024-08-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_application_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='role',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='cgpa',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='application',
            name='education',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='native',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='phoneNumber',
            field=models.CharField(max_length=15),
        ),
    ]
